from __future__ import annotations

import io
import json
import re

import openpyxl

from app.models.report import AggregatedSummary
from app.services.excel_export import ExcelExportService
from app.utils.filename_parser import output_filename


class ReportMergeService:
    def parse_report_filename(self, filename: str) -> tuple[str, str]:
        """
        Parse from_date and to_date out of filenames like:
        report_commercial_01-06-2026_to_07-06-2026.xlsx
        Returns ISO dates (YYYY-MM-DD).
        """
        m = re.search(r"(\d{2}-\d{2}-\d{4})_to_(\d{2}-\d{2}-\d{4})", filename)
        if not m:
            raise ValueError(f"Cannot parse date range from filename: {filename}")
        return self._dmy_to_iso(m.group(1)), self._dmy_to_iso(m.group(2))

    @staticmethod
    def _dmy_to_iso(s: str) -> str:
        d, mo, y = s.split("-")
        return f"{y}-{mo}-{d}"

    def read_report_data(self, xlsx_bytes: bytes) -> dict:
        wb = openpyxl.load_workbook(io.BytesIO(xlsx_bytes), data_only=True)
        if "_data" not in wb.sheetnames:
            raise ValueError(
                "File is missing the '_data' sheet. "
                "Only reports generated by this application can be merged."
            )
        raw = wb["_data"]["A1"].value
        return json.loads(raw)

    def merge(self, report_files: list[tuple[str, bytes]]) -> tuple[bytes, str]:
        """
        Returns (excel_bytes, output_filename).
        Raises ValueError on validation failure.
        """
        aggregated: dict[str, AggregatedSummary] = {}
        date_ranges: list[tuple[str, str]] = []

        for filename, content in report_files:
            from_date, to_date = self.parse_report_filename(filename)
            date_ranges.append((from_date, to_date))
            data = self.read_report_data(content)
            for portfolio, summary_data in data.items():
                aggregated[portfolio] = AggregatedSummary(
                    portfolio=portfolio,
                    from_date=summary_data["from_date"],
                    to_date=summary_data["to_date"],
                    data_source_summary=summary_data["data_source_summary"],
                    error_summary=summary_data["error_summary"],
                )

        if len(set(date_ranges)) > 1:
            ranges_str = ", ".join(f"{f} to {t}" for f, t in set(date_ranges))
            raise ValueError(
                f"Uploaded reports have mismatched date ranges: {ranges_str}"
            )

        excel_bytes = ExcelExportService().generate(aggregated)
        portfolios = list(aggregated.keys())
        from_date = min(s.from_date for s in aggregated.values())
        to_date = max(s.to_date for s in aggregated.values())
        fname = output_filename(portfolios, from_date, to_date)
        return excel_bytes, fname
